import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
	MatToolbarModule,
	MatButtonModule,
	MatSidenavModule,
	MatIconModule,
	MatListModule,
	MatCardModule,
	MatInputModule,
	MatProgressSpinnerModule,
	MatGridListModule,
	MatMenuModule,
	MatTableModule,
	MatSnackBarModule,
	MatDialogModule,
	MatCheckboxModule,
	MatRadioModule,
	MatSelectModule,
	MatPaginatorModule,
	MatProgressBarModule,
	MatTooltipModule,
	MatChipsModule,
	MatAutocompleteModule,
	MatFormFieldModule,

} from '@angular/material';

@NgModule({
	declarations: [],
	imports: [
		CommonModule,
		MatToolbarModule,
		MatButtonModule,
		MatSidenavModule,
		MatIconModule,
		MatListModule,
		MatCardModule,
		MatInputModule,
		MatProgressSpinnerModule,
		MatGridListModule,
		MatMenuModule,
		MatTableModule,
		MatSnackBarModule,
		MatDialogModule,
		MatCheckboxModule,
		MatRadioModule,
		MatSelectModule,
		MatPaginatorModule,
		MatProgressBarModule,
		MatTooltipModule,
		MatChipsModule,
		MatAutocompleteModule,
		MatFormFieldModule
	],
	exports: [
		CommonModule,
		MatToolbarModule,
		MatButtonModule,
		MatSidenavModule,
		MatIconModule,
		MatListModule,
		MatCardModule,
		MatInputModule,
		MatProgressSpinnerModule,
		MatGridListModule,
		MatMenuModule,
		MatTableModule,
		MatSnackBarModule,
		MatDialogModule,
		MatCheckboxModule,
		MatRadioModule,
		MatSelectModule,
		MatPaginatorModule,
		MatProgressBarModule,
		MatTooltipModule,
		MatChipsModule,
		MatAutocompleteModule,
		MatFormFieldModule
	]
})
export class MaterialModule { }
